version: '3'

services:
  website_dev:
    build:
      context: .
      dockerfile: docker_dev/Dockerfile
    image: hubrise/website-dev
    container_name: website_dev
    environment:
      - NODE_ENV=local
      - SENTRY_DSN=https://96b4d1defd7648308c6e30f8a3470cfd@sentry.io/1776244
      - RECAPTCHA_SITE_KEY=6LfjbNYUAAAAAPx_tCv_YyhueK2JIjf58b2HGU8d
      - CONTACT_MESSAGE_URL=http://manager.hubrise.localtest.me:4003/api/contact_message
    volumes:
      - .:/var/www/website
    ports:
      - "8000:8000"

  website_test:
    build:
      context: .
      dockerfile: docker_dev/Dockerfile
    image: hubrise/website-dev
    container_name: website_test
    environment:
      - NODE_ENV=local
      - SENTRY_DSN=https://96b4d1defd7648308c6e30f8a3470cfd@sentry.io/1776244
      - RECAPTCHA_SITE_KEY=6LfjbNYUAAAAAPx_tCv_YyhueK2JIjf58b2HGU8d
      - CONTACT_MESSAGE_URL=http://localhost/api/contact_message
    volumes:
      - .:/var/www/website
    command: /usr/local/bin/yarn test:all:ci

  website_prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: hubrise/website
    container_name: website_prod
    environment:
      - NODE_ENV=production
      - SENTRY_DSN=https://96b4d1defd7648308c6e30f8a3470cfd@sentry.io/1776244
      - RECAPTCHA_SITE_KEY=6LfjbNYUAAAAAPx_tCv_YyhueK2JIjf58b2HGU8d
      - CONTACT_MESSAGE_URL=https://manager.hubrise.com/api/contact_message
    ports:
      - "8001:80"
