kind: Deployment
apiVersion: apps/v1

metadata:
  name: website
  labels:
    app: website

spec:
  selector:
    matchLabels:
      app: website

  # CLUSTER  replicas: 1

  template:
    metadata:
      labels:
        app: website

    spec:
      imagePullSecrets:
        - name: docker-credentials

      containers:
        - name: website
          image: hubrise/website

          readinessProbe:
            httpGet:
              path: /api/live
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/live
              port: 80
            periodSeconds: 15

  revisionHistoryLimit: 2
