name: cypress

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run cypress

    # To upgrade to the latest version, see https://hub.docker.com/r/cypress/browsers/tags
    container: cypress/browsers:node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js and package cache
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'yarn'

      - name: Cache gatsby build files
        uses: actions/cache@v3
        with:
          path: |
            .cache
            public
          key: gatsby-build-${{ hashFiles('./yarn.lock') }}

      - name: Install JS dependencies
        run: yarn install

      - name: Build the website
        run: yarn build

      - name: Run Cypress test suite
        env:
          NODE_ENV: test
          SENTRY_DSN: https://96b4d1defd7648308c6e30f8a3470cfd@sentry.io/1776244
          RECAPTCHA_SITE_KEY: 6LfjbNYUAAAAAPx_tCv_YyhueK2JIjf58b2HGU8d
          CONTACT_MESSAGE_URL: http://localhost/api/contact_message
          WAIT_ON_TIMEOUT: 1200000 # (in milliseconds) 20 minute timeout for start-server-and-test
        run: yarn cypress:run
