name: cypress

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run cypress

    # To upgrade to the latest version, see https://github.com/cypress-io/cypress-docker-images/tree/master/browsers
    container: cypress/browsers:node14.17.0-chrome91-ff89

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install JS dependencies
        run: yarn install

      - name: Build the website
        run: yarn build

      - name: Run Cypress test suite
        env:
          NODE_ENV: test
          SENTRY_DSN: https://96b4d1defd7648308c6e30f8a3470cfd@sentry.io/1776244
          RECAPTCHA_SITE_KEY: 6LfjbNYUAAAAAPx_tCv_YyhueK2JIjf58b2HGU8d
          CONTACT_MESSAGE_URL: http://localhost/api/contact_message
          WAIT_ON_TIMEOUT: 1200000 # (in milliseconds) 20 minute timeout for start-server-and-test
        run: yarn test:e2e
