name: spec

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run all specs

    container:
      image: node:14.17.0-buster

    steps:
      - name: Clone repository
        uses: actions/checkout@v1

#      - name: Install Linux packages required by Cypress
#        run: |
#          apt-get update
#          apt-get install -y xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
#
#      - name: Install JS dependencies
#        run: yarn install
#
#      - name: Run tests
#        env:
#          NODE_ENV: test
#          SENTRY_DSN: https://96b4d1defd7648308c6e30f8a3470cfd@sentry.io/1776244
#          RECAPTCHA_SITE_KEY: 6LfjbNYUAAAAAPx_tCv_YyhueK2JIjf58b2HGU8d
#          CONTACT_MESSAGE_URL: http://localhost/api/contact_message
#          WAIT_ON_TIMEOUT: 1200000 # (in milliseconds) 20 minute timeout for start-server-and-test
#        run: yarn test:all:ci
